version: "3"
services:
  knowledgegraph:
    build:
      context: ./neo4j/
    container_name: knowledgegraph
    entrypoint:
      - /bin/sh
      - -c
      - "chown neo4j:neo4j /ssl && /docker-entrypoint.sh neo4j"
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk/jre
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_dbms_connectors_default__listen__address=0.0.0.0
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*  # un-sandbox apoc procedures: http://blog.armbruster-it.de/2017/05/running-neo4j-3-2-apoc-docker/
      - NEO4J_dbms_memory_heap_max__size=${NEO4J_HEAP_MEMORY}
      - NEO4J_dbms_memory_heap_initial__size=${NEO4J_HEAP_MEMORY_INIT}
      - NEO4J_dbms_memory_pagecache_size=${NEO4J_CACHE_MEMORY}
      - NEO4J_dbms_read__only=${NEO4J_READONLY}
      - NEO4J_dbms_jvm_additional=-XX:+UnlockExperimentalVMOptions -XX:+UseZGC
    ports:
      - "${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}"
      - "${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}"
    volumes:
      - ../../../neo4j_data:/data
      - ../../../neo4j_logs:/logs
      - ../../../neo4j_ssl:/ssl